version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  app-server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  react-app:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - app-server
